services:
  gate:
    image: ghcr.io/ralacher/gate-keeper:latest
    container_name: gate-keeper
    restart: unless-stopped
    ports:
      - "3080:80"
    environment:
      - HA_BASE_URL=${HA_BASE_URL}
      - GO2RTC_URL=${GO2RTC_URL}