import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by vite-plugin-pwa
precacheAndRoute(self.__WB_MANIFEST)

// ── Push notification handler ────────────────────────────────
self.addEventListener('push', (event) => {
  if (!event.data) return

  let data
  try {
    data = event.data.json()
  } catch {
    data = { title: 'Gate Activity', body: event.data.text() }
  }

  const { title = 'Gate Activity', body = '', icon = '/gate-icon-192.png', tag = 'gate-activity' } = data

  event.waitUntil(
    self.registration.showNotification(title, {
      body,
      icon,
      tag, // replaces previous notification with same tag
      badge: '/gate-icon-192.png',
      data: { url: '/' },
    }),
  )
})

// ── Open app when notification is clicked ────────────────────
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const url = event.notification.data?.url || '/'

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      // Focus existing tab if open
      for (const client of clients) {
        if (new URL(client.url).pathname === url && 'focus' in client) {
          return client.focus()
        }
      }
      // Otherwise open a new tab
      return self.clients.openWindow(url)
    }),
  )
})
